routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index');
Route::get('about', 'AboutController@index')->name('about');
Route::get('style', 'StyleController@index')->name('style');
Route::get('/service', 'ServiceController@index');
Route::get('recruit', 'RecruitController@index')->name('recruit');
Route::get('contact', 'ContactController@index')->name('contact');
Route::get('blog', 'BlogController@index')->name('blog');
Route::get('blog/category/{id}', 'BlogController@category');
Route::get('blog/tag/{id}', 'BlogController@tag');
Route::get('blog/{id}/detail', 'BlogController@detail');
Route::get('blog/search', 'BlogController@search');
Route::get('/event', 'EventController@index');
Route::get('/event/{id}/detail', 'EventController@detail');
Route::get('/gallery', 'GalleryController@index');
Route::get('/recruit', 'RecruitController@index');
Route::get('/sitemap', 'SitemapController@index');
Route::get('/team', 'TeamController@index');
Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

app/Models/Event.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use DB;
use Carbon\Carbon;

class Event extends Model
{
    protected $fillable = array('title', 'organization', 'start_date', 'end_date' , 'address','quantity','content', 'photo');
    protected $table = 'events';
    
    public function getStartDateAttribute()
	{
	    return Carbon::parse($this->attributes['start_date']); 
	}

	public function getEndDateAttribute()
	{
	    return Carbon::parse($this->attributes['end_date']); 
	}

    public function getPhotoFormatAttribute($value)
    {
        return DB::table('photos')->whereIn('id', explode(',', $this->photo))->get();
    }
}

resources/views/about.blade.php
@extends('layouts.app')
@section('main-content')

	<section class="page-header">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<ul class="breadcrumb">
						<li><a href="#">Home</a></li>
						<li class="active">About Us</li>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<h1>About Us</h1>
				</div>
			</div>
		</div>
	</section>

	<div class="container">

		<div class="row">
			<div class="col-md-12">
				<h2 class="word-rotator-title">
					The New Way to <strong>
						<span class="word-rotate" data-plugin-options="{'delay': 2000}">
							<span class="word-rotate-items">
								<span>success.</span>
								<span>advance.</span>
								<span>progress.</span>
							</span>
						</span>
					</strong>
				</h2>
			</div>
		</div>

		<div class="row">
			<div class="col-md-10">
				<p class="lead">
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum pellentesque imperdiet. Nulla lacinia iaculis nulla non <span class="alternative-font">metus.</span> pulvinar. Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut eu risus enim, ut pulvinar lectus. Sed hendrerit nibh.
				</p>
			</div>
			<div class="col-md-2">
				<a href="#" class="btn btn-lg btn-primary mt-xl">Join Our Team!</a>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				<hr class="tall">
			</div>
		</div>

		<div class="row">
			<div class="col-md-8">
				<h3 class="heading-primary"><strong>Who</strong> We Are</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc <a href="#">vehicula</a> lacinia. Proin adipiscing porta tellus, ut feugiat nibh adipiscing sit amet. In eu justo a felis faucibus ornare vel id metus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In eu libero ligula. Fusce eget metus lorem, ac viverra leo. Nullam convallis, arcu vel pellentesque sodales, nisi est varius diam, ac ultrices sem ante quis sem. Proin ultricies volutpat sapien, nec scelerisque ligula mollis lobortis.</p>
				<p>Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut feugiat nibh adipiscing <span class="alternative-font">metus</span> sit amet. In eu justo a felis faucibus ornare vel id metus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In eu libero ligula. Fusce eget metus lorem, ac viverra leo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In eu libero ligula. Fusce eget metus lorem, ac viverra leo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In eu libero ligula.</p>
			</div>
			<div class="col-md-4">
				<div class="featured-box featured-box-primary">
					<div class="box-content">
						<h4 class="text-uppercase">Behind the scenes</h4>
						<ul class="thumbnail-gallery" data-plugin-lightbox data-plugin-options="{'delegate': 'a', 'type': 'image', 'gallery': {'enabled': true}}">
							<li>
								<a title="Benefits 1" href="img/benefits/benefits-1.jpg">
									<span class="thumbnail mb-none">
										<img src="img/benefits/benefits-1-thumb.jpg" alt="">
									</span>
								</a>
							</li>
							<li>
								<a title="Benefits 2" href="img/benefits/benefits-2.jpg">
									<span class="thumbnail mb-none">
										<img src="img/benefits/benefits-2-thumb.jpg" alt="">
									</span>
								</a>
							</li>
							<li>
								<a title="Benefits 3" href="img/benefits/benefits-3.jpg">
									<span class="thumbnail mb-none">
										<img src="img/benefits/benefits-3-thumb.jpg" alt="">
									</span>
								</a>
							</li>
							<li>
								<a title="Benefits 4" href="img/benefits/benefits-4.jpg">
									<span class="thumbnail mb-none">
										<img src="img/benefits/benefits-4-thumb.jpg" alt="">
									</span>
								</a>
							</li>
							<li>
								<a title="Benefits 5" href="img/benefits/benefits-5.jpg">
									<span class="thumbnail mb-none">
										<img src="img/benefits/benefits-5-thumb.jpg" alt="">
									</span>
								</a>
							</li>
							<li>
								<a title="Benefits 6" href="img/benefits/benefits-6.jpg">
									<span class="thumbnail mb-none">
										<img src="img/benefits/benefits-6-thumb.jpg" alt="">
									</span>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				<hr class="tall">
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				<h3 class="heading-primary mt-xl">Our <strong>History</strong></h3>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">

				<ul class="history">
					<li class="appear-animation" data-appear-animation="fadeInUp">
						<div class="thumb">
							<img src="img/office/office-4.jpg" alt="" />
						</div>
						<div class="featured-box">
							<div class="box-content">
								<h4 class="heading-primary"><strong>2012</strong></h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus,</p>
							</div>
						</div>
					</li>
					<li class="appear-animation" data-appear-animation="fadeInUp">
						<div class="thumb">
							<img src="img/office/office-3.jpg" alt="" />
						</div>
						<div class="featured-box">
							<div class="box-content">
								<h4 class="heading-primary"><strong>2010</strong></h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia.</p>
							</div>
						</div>
					</li>
					<li class="appear-animation" data-appear-animation="fadeInUp">
						<div class="thumb">
							<img src="img/office/office-2.jpg" alt="" />
						</div>
						<div class="featured-box">
							<div class="box-content">
								<h4 class="heading-primary"><strong>2005</strong></h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus,</p>
							</div>
						</div>
					</li>
					<li class="appear-animation" data-appear-animation="fadeInUp">
						<div class="thumb">
							<img src="img/office/office-1.jpg" alt="" />
						</div>
						<div class="featured-box">
							<div class="box-content">
								<h4 class="heading-primary"><strong>2000</strong></h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus,</p>
							</div>
						</div>
					</li>
				</ul>

			</div>
		</div>

	</div>

@endsection

resources/views/contact.blade.php
@extends('layouts.app')
@section('main-content')
	<section class="page-header">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<ul class="breadcrumb">
						<li><a href="/">Home</a></li>
						<li class="active">Contact Us</li>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<h1>Contact Us</h1>
				</div>
			</div>
		</div>
	</section>

	<!-- Google Maps - Go to the bottom of the page to change settings and map location. -->
	<div id="googlemaps" class="google-map"></div>

	<div class="container">

		<div class="row">
			<div class="col-md-6">
				
				@if(Session::has('messages'))
				<div class="alert alert-success mt-lg" id="contactSuccess">
					{!! Session::get('messages') !!}
				</div>
				@endif
				@if($errors->any())
				<div class="alert alert-danger mt-lg" id="contactError">
					<strong>Error!</strong> There was an error sending your message.<br>
					@foreach($errors->all() as $error)
							<strong>{{ $error }}</strong><br>
					@endforeach
					<span class="font-size-xs mt-sm display-block" id="mailErrorMessage"></span>
				</div>
				@endif

				<h2 class="mb-sm mt-sm"><strong>Contact</strong> Us</h2>
						
				
				{!! Form::open(['url'=>'/contact']) !!}
					
					<div class="row">
						<div class="form-group">
							<div class="col-md-6">
								<label>Your name *</label>
								<input type="text" value="{{ old('name') }}" data-msg-required="Please enter your name." maxlength="100" class="form-control" name="name" id="name" required>
								@if ($errors->has('name'))<span class="help-block">{{ $errors->first('name') }}</span>@endif
							</div>
							<div class="col-md-6">
								<label>Your email address *</label>
								<input type="email" value="{{ old('email') }}" data-msg-required="Please enter your email address." data-msg-email="Please enter a valid email address." maxlength="100" class="form-control" name="email" id="email" required>
								@if ($errors->has('email'))<span class="help-block">{{ $errors->first('email') }}</span>@endif
							</div>
						</div>
					</div>
					<div class="row">
						<div class="form-group">
							<div class="col-md-6">
								<label>Your phone *</label>
								<input type="text" value="{{ old('phone') }}" data-msg-required="Please enter your phone." maxlength="100" class="form-control" name="phone" id="phone" required>
								@if ($errors->has('phone'))<span class="help-block">{{ $errors->first('phone') }}</span>@endif
							</div>
							<div class="col-md-6">
								<label>Your address *</label>
								<input type="text" value="{{ old('address') }}" data-msg-required="Please enter your address." maxlength="100" class="form-control" name="address" id="address" required>
								@if ($errors->has('address'))<span class="help-block">{{ $errors->first('address') }}</span>@endif
							</div>
						</div>
					</div>
					<div class="row">
						<div class="form-group">
							<div class="col-md-12">
								<label>Subject</label>
								<input type="text" value="{{ old('title') }}" data-msg-required="Please enter the subject." maxlength="100" class="form-control" name="title" id="subject" required>
								@if ($errors->has('title'))<span class="help-block">{{ $errors->first('title') }}</span>@endif
							</div>
						</div>
					</div>
					<div class="row">
						<div class="form-group">
							<div class="col-md-12">
								<label>Message *</label>
								<textarea maxlength="5000" data-msg-required="Please enter your message." rows="10" class="form-control" name="content" id="message" required>{{ old('content') }}</textarea>
								@if ($errors->has('content'))<span class="help-block">{{ $errors->first('content') }}</span>@endif
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<input type="submit" value="Send Message" class="btn btn-primary btn-lg mb-xlg" data-loading-text="Loading...">
						</div>
					</div>
				{!! Form::close() !!}
			</div>
			<div class="col-md-6">

				<h4 class="heading-primary mt-lg">Get in <strong>Touch</strong></h4>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget leo at velit imperdiet varius. In eu ipsum vitae velit congue iaculis vitae at risus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>

				<hr>

				<h4 class="heading-primary">The <strong>Office</strong></h4>
				<ul class="list list-icons list-icons-style-3 mt-xlg">
					<li><i class="fa fa-map-marker"></i> <strong>Address:</strong> 1234 Street Name, City Name, United States</li>
					<li><i class="fa fa-phone"></i> <strong>Phone:</strong> (123) 456-789</li>
					<li><i class="fa fa-envelope"></i> <strong>Email:</strong> <a href="mailto:mail@example.com">mail@example.com</a></li>
				</ul>

				<hr>

				<h4 class="heading-primary">Business <strong>Hours</strong></h4>
				<ul class="list list-icons list-dark mt-xlg">
					<li><i class="fa fa-clock-o"></i> Monday - Friday - 9am to 5pm</li>
					<li><i class="fa fa-clock-o"></i> Saturday - 9am to 2pm</li>
					<li><i class="fa fa-clock-o"></i> Sunday - Closed</li>
				</ul>

			</div>

		</div>

	</div>
@endsection
@section('addhtml')
	<section class="call-to-action call-to-action-default with-button-arrow call-to-action-in-footer">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="call-to-action-content">
						<h3>Porto is <strong>everything</strong> you need to create an <strong>awesome</strong> website!</h3>
						<p>The <strong>#1 Selling</strong> HTML Site Template on ThemeForest</p>
					</div>
					<div class="call-to-action-btn">
						<a href="http://themeforest.net/item/porto-responsive-html5-template/4106987" target="_blank" class="btn btn-lg btn-primary">Buy Now!</a><span class="arrow hlb hidden-xs hidden-sm hidden-md" data-appear-animation="rotateInUpLeft" style="top: -12px;"></span>
					</div>
				</div>
			</div>
		</div>
	</section>
@stop
@section('javascript')
		<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC-CQdWN5u3kMi04OJEbDgDnxZFh7qlEG8"></script>
		<script>
			/*
			Map Settings

				Find the Latitude and Longitude of your address:
					- http://universimmedia.pagesperso-orange.fr/geo/loc.htm
					- http://www.findlatitudeandlongitude.com/find-address-from-latitude-and-longitude/

			*/
			// Map Markers
			var mapMarkers = [{
				address: "New York, NY 10017",
				html: "<strong>New York Office</strong><br>New York, NY 10017",
				icon: {
					image: "/img/pin.png",
					iconsize: [26, 46],
					iconanchor: [12, 46]
				},
				popup: true
			}];

			// Map Initial Location
			var initLatitude = 10.7513756;
			var initLongitude = 106.6939804;

			// Map Extended Settings
			var mapSettings = {
				controls: {
					panControl: true,
					zoomControl: true,
					mapTypeControl: true,
					scaleControl: true,
					streetViewControl: true,
					overviewMapControl: true
				},
				scrollwheel: false,
				markers: mapMarkers,
				latitude: initLatitude,
				longitude: initLongitude,
				zoom: 16
			};

			var map = $('#googlemaps').gMap(mapSettings);

			// Map Center At
			var mapCenterAt = function(options, e) {
				e.preventDefault();
				$('#googlemaps').gMap("centerAt", options);
			}

		</script>

		<!-- Google Analytics: Change UA-XXXXX-X to be your site's ID. Go to http://www.google.com/analytics/ for more information.
		<script>
			(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		
			ga('create', 'UA-12345678-1', 'auto');
			ga('send', 'pageview');
		</script>
		 -->
@stop

resources/views/gallery.blade.php
@extends('layouts.app')
@section('main-content')
	<section class="page-header">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<ul class="breadcrumb">
						<li><a href="/">Home</a></li>
						<li class="active">Shortcodes</li>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<h1>Image Gallery</h1>
				</div>
			</div>
		</div>
	</section>
@if(isset($albums) && $albums->count())
@foreach($albums as $album)
	<div class="container">

		<div class="row">
			<div class="col-md-12">
				<hr class="tall">
				<h4>{{ $album->name }}</h4>
			</div>
		</div>
	</div>

	<ul class="image-gallery sort-destination full-width">
		@foreach($album->photo as $k => $v)
		<li class="isotope-item">
			<div class="image-gallery-item">
				<a href="javascript:;">
					<span class="thumb-info thumb-info-centered-info thumb-info-no-borders">
						<span class="thumb-info-wrapper">
							<img src="{{ $v->url }}" class="img-responsive" alt="">
							<span class="thumb-info-action">
								<span class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
							</span>
						</span>
					</span>
				</a>
			</div>
		</li>
		@endforeach
	</ul>
@endforeach
@endif
	{{-- <div class="container">

		<div class="row">
			<div class="col-md-12">
				<hr class="tall">

				<h4>{{ $album->name }}</h4>

				<div class="masonry-loader masonry-loader-showing">
					<div class="masonry" data-plugin-masonry data-plugin-options="{'itemSelector': '.masonry-item'}">
						@foreach($album->photo as $k => $v)
						<div class="masonry-item">
							<a href="javascript:;">
								<span class="thumb-info thumb-info-centered-info thumb-info-no-borders">
									<span class="thumb-info-wrapper">
										<img src="{{ $v->url }}" class="img-responsive" alt="">
										<span class="thumb-info-action">
											<span class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
										</span>
									</span>
								</span>
							</a>
						</div>
						@endforeach
					</div>
				</div>
			</div>
		</div>

	</div> --}}
@endsection

@section('javascript')
	<!-- Examples -->
	<script src="/js/examples/examples.gallery.js"></script>
@stop

resources/views/my_menu.blade.php
<ul class="nav nav-pills" id="mainNav">
	@foreach($items as $menu_item)
		@php
            $submenu = $menu_item->children;
        @endphp
        @if(isset($submenu) && $submenu->count())
        	<li class="dropdown">
        		<a href="{{ $menu_item->link() }}" class="dropdown-toggle">{{ $menu_item->title }}</a>
	        	<ul class="dropdown-menu">
	                @foreach($submenu as $item)
	                    <li><a href="{{$item->url}}">{{$item->title}} </a></li>
	                @endforeach
	            </ul>
            </li>
        @else
        	<li><a href="{{ $menu_item->link() }}">{{ $menu_item->title }}</a></li>
        @endif
    @endforeach

</ul>

resources/views/sitemap.blade.php
@extends('layouts.app')
@section('main-content')
	<section class="page-header">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<ul class="breadcrumb">
						<li><a href="/">Home</a></li>
						<li class="active">Pages</li>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<h1>Sitemap</h1>
				</div>
			</div>
		</div>
	</section>

	<div class="container">

		<div class="row">

			<div class="col-md-4">
				<ul class="nav nav-list mb-xl">
					<li>
						<a href="/">@lang('strings.home')</a>
					</li>
					<li>
						<a href="/blog">@lang('strings.blogs')</a>
						<ul>
							<li><a href="/blog/search">@lang('strings.search')</a></li>
						</ul>
					</li>

					<li>
						<a href="/contact">@lang('strings.contacts')</a>
					</li>

					<li>
						<a href="/event">@lang('strings.events')</a>
					</li>

					<li>
						<a href="/gallery">@lang('strings.galleries')</a>
					</li>

					<li>
						<a href="/product">@lang('strings.products')</a>
						<ul>
							<li><a href="/product/search">@lang('strings.search')</a></li>
						</ul>
					</li>

					<li>
						<a href="/recruit">@lang('strings.recruits')</a>
					</li>

					<li>
						<a href="/service">@lang('strings.services')</a>
					</li>

					<li>
						<a href="/sitemap">@lang('strings.sitemap')</a>
					</li>

					<li>
						<a href="/team">@lang('strings.teams')</a>
					</li>
				</ul>
			</div>

			<div class="col-md-6 col-md-offset-2 hidden-xs">
				<h2 class="mb-lg">Who <strong>We Are</strong></h2>
				<p class="lead">Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut feugiat nibh adipiscing sit amet.</p>
				<ul class="list list-icons mt-xl">
					<li><i class="fa fa-check"></i>Fusce sit amet orci quis arcu vestibulum vestibulum sed ut felis. Phasellus in risus quis lectus iaculis vulputate id quis nisl.</li>
					<li><i class="fa fa-check"></i>Phasellus in risus quis lectus iaculis vulputate id quis nisl.</li>
					<li><i class="fa fa-check"></i>Fusce sit amet orci quis arcu vestibulum vestibulum sed ut felis. </li>
					<li><i class="fa fa-check"></i>Phasellus in risus quis lectus iaculis vulputate id quis nisl.</li>
					<li><i class="fa fa-check"></i>Phasellus in risus quis lectus iaculis vulputate id quis nisl.</li>
					<li><i class="fa fa-check"></i>Fusce sit amet orci quis arcu vestibulum vestibulum sed ut felis. </li>
					<li><i class="fa fa-check"></i>Phasellus in risus quis lectus iaculis vulputate id quis nisl.</li>
				</ul>
			</div>

		</div>

	</div>
@endsection

resources/views/team.blade.php
@extends('layouts.app')
@section('main-content')
	<section class="page-header">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<ul class="breadcrumb">
						<li><a href="/">Home</a></li>
						<li class="active">Pages</li>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<h1>Team</h1>
				</div>
			</div>
		</div>
	</section>

	<div class="container">

		<h2>Meet the <strong>Team</strong></h2>

		<ul class="nav nav-pills sort-source" data-sort-id="team" data-option-key="filter">
			<li data-option-value="*" class="active"><a href="javascript:;">Show All</a></li>
			@if(isset($teams))
			@foreach($teams as $team)
				<li data-option-value=".team-{{ $team->id }}"><a href="javascript:;">{{ $team->name }}</a></li>
			@endforeach
			@endif
		</ul>

		<hr>

		<div class="row">

			<div class="sort-destination-loader sort-destination-loader-showing">
				<ul class="team-list sort-destination" data-sort-id="team">
					@if(isset($members))
					@foreach($members as $member)
					<li class="col-md-3 col-sm-6 col-xs-12 isotope-item team-{{ $member->team->id }}">
						<span class="thumb-info thumb-info-hide-wrapper-bg mb-xlg">
							<span class="thumb-info-wrapper">
								<a href="javascript:;">
									@if($member->photo_format->count())
										@foreach($member->photo_format as $k => $photo)
											@if($k==0)
											<img class="img-responsive" src="{{ $photo->url }}" alt="">
											@endif
										@endforeach
									@endif
									<span class="thumb-info-title">
										<span class="thumb-info-inner">{{ $member->name }}</span>
										<span class="thumb-info-type">{{ $member->position }}</span>
									</span>
								</a>
							</span>
							<span class="thumb-info-caption">
								<span class="thumb-info-caption-text">{!! $member->description !!}</span>
								@if(!empty($member->social) && $member->social_array)
								    <span class="thumb-info-social-icons">
								  @foreach($member->social_array as $sa)
								    @foreach($sa as $k => $s)

								    	<a target="_blank" href="{{ $s }}"><i class="fa fa-{{ $k }}"></i></a>

								    @endforeach
								  @endforeach
								    </span>
								@endif
								
							</span>
						</span>
					</li>
					@endforeach
					@endif
				</ul>
			</div>

		</div>

	</div>
@endsection